In [1]:
import numpy as np
import pandas as pd

In [2]:
# PIVOT TABLES

In [5]:
data = {
    'Date': pd.date_range('2023-01-01', periods = 20),
    'Product': ['A', 'B', 'C', 'D']  * 5,
    'Region': ['East', 'west', 'north', 'south' ,'East', 'west', 'north', 'south', 'East', 'west',
               'north', 'south', 'East', 'west', 'north', 'south', 'East', 'west', 'north', 'south'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['john', 'mary', 'bob', 'alice', 'john', 'mary', 'bob', 'alice','john', 'mary', 
            'bob', 'alice','john', 'mary', 'bob', 'alice','john', 'mary', 'bob', 'alice']

}
df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)

In [6]:
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    804     34   john  January      Q1
1  2023-01-02       B   west    499     85   mary  January      Q1
2  2023-01-03       C  north    939     68    bob  January      Q1
3  2023-01-04       D  south    408     10  alice  January      Q1
4  2023-01-05       A   East    629     21   john  January      Q1
5  2023-01-06       B   west    589     95   mary  January      Q1
6  2023-01-07       C  north    136     99    bob  January      Q1
7  2023-01-08       D  south    712     95  alice  January      Q1
8  2023-01-09       A   East    354     16   john  January      Q1
9  2023-01-10       B   west    769     69   mary  January      Q1
10 2023-01-11       C  north    566     74    bob  January      Q1
11 2023-01-12       D  south    684     92  alice  January      Q1
12 2023-01-13       A   East    281     42   john  January      Q1
13 2023-01-14       B   west    184     73   mary  January      Q1
14 2023-01-15       C  north    327     43    bob  January      Q1
15 2023-01-16       D  south    720     85  alice  January      Q1
16 2023-01-17       A   East    391     60   john  January      Q1
17 2023-01-18       B   west    646     61   mary  January      Q1
18 2023-01-19       C  north    247     40    bob  January      Q1
19 2023-01-20       D  south    614     33  alice  January      Q1

In [10]:
pd.pivot_table(df,values = "Sales", index = 'Region',columns = "Product",aggfunc = 'median')

Product      A      B      C      D
Region
East     391.0    NaN    NaN    NaN
north      NaN    NaN  327.0    NaN
south      NaN    NaN    NaN  684.0
west       NaN  589.0    NaN    NaN

In [12]:
pivot2 = pd.pivot_table(df,values = ["Sales", "Units"] ,index = 'Region',columns = "Product")
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     491.8    NaN    NaN    NaN  34.6   NaN   NaN   NaN
north      NaN    NaN  443.0    NaN   NaN   NaN  64.8   NaN
south      NaN    NaN    NaN  627.6   NaN   NaN   NaN  63.0
west       NaN  537.4    NaN    NaN   NaN  76.6   NaN   NaN

In [ ]:
# CROSS TABS

In [13]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
north    0  0  5  0
south    0  0  0  5
west     0  5  0  0